prometheus:
  url: http://kps-kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090

rules:
  default: false
  custom:
    - seriesQuery: 'http_requests_total{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: { resource: "namespace" }
          pod: { resource: "pod" }
      name:
        matches: "http_requests_total"
        as: "rps_per_pod"
      metricsQuery: 'sum by (<<.GroupBy>>) (rate(http_requests_total{<<.LabelMatchers>>}[1m]))'